пуш на сервер

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -85,8 +85,33 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-    needs: [build-backend, build-frontend]  # Зависимость от завершения сборки обоих образов
+    needs: [ build-backend, build-frontend ]  # Зависимость от завершения сборки обоих образов
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          submodules: true  # Загружаем подмодули, если они есть
+          fetch-depth: 0  # Клонируем весь репозиторий
+
+      - name: Copy docker-compose.yaml to server
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          source: "docker-compose.yaml" # Путь к файлу, как в структуре вашего проекта
+          target: "/root/str/" # Удаленный путь на сервере
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USER }}
+          key: ${{ secrets.SSH_KEY }}
+
+      - name: Copy nginx directory to server
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          source: "nginx/*"
+          target: "/root/str/nginx/"
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USER }}
+          key: ${{ secrets.SSH_KEY }}
+          strip_components: 1 # Убирает одну вложенность
+
       - name: Deploy to server
         uses: appleboy/ssh-action@v0.1.7
         with:
@@ -94,10 +119,21 @@ jobs:
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_KEY }}
           script: |
+            # Переход в директорию проекта
+            cd /root/str
+            
+            # Проверка наличия docker-compose.yaml
+            if [ ! -f docker-compose.yaml ]; then
+              echo "docker-compose.yaml not found!"
+              exit 1
+            fi
+            echo "docker-compose.yaml found."
+            
+            # Создание файла .env с переменными окружения
             rm -f .env
             touch .env
             chmod 600 .env
-
+            
             echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
             echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
             echo DB_NAME=${{ secrets.DB_NAME }} >> .env
@@ -105,16 +141,14 @@ jobs:
             echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
             echo DB_HOST=${{ secrets.DB_HOST }} >> .env
             echo DB_PORT=${{ secrets.DB_PORT }} >> .env
-
+            
             echo "Contents of .env:"
             cat .env
-
+            
             # Запуск docker-compose
-            docker compose pull
-            docker compose up -d --build
-      
+            docker compose pull || docker-compose pull
+            docker compose up -d --build || docker-compose up -d --build
 
-      # 7. (Optional) Notify about the deployment status
       - name: Notify success
         if: success()
         run: echo "Deployment was successful!"
