фронтенд изменения

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,8 +37,8 @@ jobs:
       - name: Build and push backend image
         uses: docker/build-push-action@v3
         with:
-          context: .  # Указываем корень репозитория как контекст
-          file: Dockerfile  # Dockerfile находится в корне репозитория
+          context: .
+          file: Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
 
@@ -69,10 +69,9 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest
 
-
   deploy:
     runs-on: ubuntu-latest
-    needs: [ build-backend, build-nginx ]
+    needs: [build-backend, build-nginx]
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -91,8 +90,9 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           script: |
             cd /root/str
-            docker compose down --volumes --remove-orphans
-            docker volume rm $(docker volume ls -qf dangling=true) || true
+            docker compose down --remove-orphans
+            # Удаляем только осиротевшие тома, исключая том с базой данных
+            docker volume rm $(docker volume ls -qf "dangling=true" | grep -v "postgres_data") || true
 
       - name: Copy docker-compose.yaml to server
         uses: appleboy/scp-action@v0.1.7
@@ -144,9 +144,9 @@ jobs:
             echo "Contents of .env:"
             cat .env
 
-            # Запуск docker compose
+            # Запуск обновления образов и контейнеров
             docker compose pull
-            docker compose up -d
+            docker compose up -d --build
 
       - name: Notify success
         if: success()
@@ -167,8 +167,8 @@ jobs:
 #      - name: Checkout code
 #        uses: actions/checkout@v3
 #        with:
-#          submodules: true  # Загружаем подмодули, если они есть
-#          fetch-depth: 0  # Клонируем весь репозиторий
+#          submodules: true
+#          fetch-depth: 0
 #
 #      - name: Verify backend directory contents
 #        run: |
@@ -197,78 +197,63 @@ jobs:
 #          push: true
 #          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
 #
-##  build-frontend:
-##    runs-on: ubuntu-latest
-##    needs: build-backend  # Ждем завершения сборки backend
-##    steps:
-##      - name: Checkout code
-##        uses: actions/checkout@v3
-##        with:
-##          submodules: true  # Загружаем подмодули, если они есть
-##          fetch-depth: 0  # Клонируем весь репозиторий
-##
-##      - name: Update submodules
-##        run: git submodule update --init --recursive
-##        # Обновляем и инициализируем подмодули рекурсивно
-##
-##      - name: Verify frontend directory contents
-##        run: |
-##          echo "Current working directory: $(pwd)"
-##          echo "Contents of root directory:"
-##          ls -la
-##          echo "Contents of frontend directory:"
-##          ls -la ./frontend
-##          echo "Dockerfile contents:"
-##          cat ./frontend/Dockerfile
-##
-##      - name: Set up Docker Buildx
-##        uses: docker/setup-buildx-action@v1
-##
-##      - name: Log in to Docker Hub
-##        uses: docker/login-action@v2
-##        with:
-##          username: ${{ secrets.DOCKER_USERNAME }}
-##          password: ${{ secrets.DOCKER_PASSWORD }}
-##
-##      - name: Build and push frontend image
-##        uses: docker/build-push-action@v3
-##        with:
-##          context: ./frontend  # Указываем директорию как контекст
-##          file: ./frontend/Dockerfile  # Путь к Dockerfile внутри подмодуля
-##          push: true
-##          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
-#
-#  deploy:
+#  build-nginx:
 #    runs-on: ubuntu-latest
-#    needs: [ build-backend, build-frontend ]  # Зависимость от завершения сборки обоих образов
+#    needs: build-backend
 #    steps:
 #      - name: Checkout code
 #        uses: actions/checkout@v3
 #        with:
-#          submodules: true  # Загружаем подмодули, если они есть
-#          fetch-depth: 0  # Клонируем весь репозиторий
-#      - name: Remove unused Docker images
-#        run: |
-#          docker image prune -f
+#          submodules: true
+#          fetch-depth: 0
 #
-#      - name: Clean up old Docker containers and images
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v1
+#
+#      - name: Log in to Docker Hub
+#        uses: docker/login-action@v2
+#        with:
+#          username: ${{ secrets.DOCKER_USERNAME }}
+#          password: ${{ secrets.DOCKER_PASSWORD }}
+#
+#      - name: Build and push nginx image
+#        uses: docker/build-push-action@v3
+#        with:
+#          context: .
+#          file: nginx/nginx.Dockerfile
+#          push: true
+#          tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest
+#
+#
+#  deploy:
+#    runs-on: ubuntu-latest
+#    needs: [ build-backend, build-nginx ]
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#        with:
+#          submodules: true
+#          fetch-depth: 0
+#
+#      - name: Remove unused Docker images
+#        run: docker image prune -f
+#
+#      - name: Clean up old Docker containers and images on server
 #        uses: appleboy/ssh-action@v0.1.7
 #        with:
 #          host: ${{ secrets.HOST }}
 #          username: ${{ secrets.USER }}
 #          key: ${{ secrets.SSH_KEY }}
 #          script: |
-#            # Останавливаем и удаляем старые контейнеры
-#            docker container prune -f
-#
-#            # Удаляем старые, неиспользуемые образы
-#            docker image prune -f
+#            cd /root/str
+#            docker compose down --volumes --remove-orphans
+#            docker volume rm $(docker volume ls -qf dangling=true) || true
 #
 #      - name: Copy docker-compose.yaml to server
 #        uses: appleboy/scp-action@v0.1.7
 #        with:
-#          source: "docker-compose.yaml" # Путь к файлу, как в структуре вашего проекта
-#          target: "/root/str/" # Удаленный путь на сервере
+#          source: "docker-compose.yaml"
+#          target: "/root/str/"
 #          host: ${{ secrets.HOST }}
 #          username: ${{ secrets.USER }}
 #          key: ${{ secrets.SSH_KEY }}
@@ -281,7 +266,7 @@ jobs:
 #          host: ${{ secrets.HOST }}
 #          username: ${{ secrets.USER }}
 #          key: ${{ secrets.SSH_KEY }}
-#          strip_components: 1 # Убирает одну вложенность
+#          strip_components: 1
 #
 #      - name: Deploy to server
 #        uses: appleboy/ssh-action@v0.1.7
@@ -290,17 +275,15 @@ jobs:
 #          username: ${{ secrets.USER }}
 #          key: ${{ secrets.SSH_KEY }}
 #          script: |
-#            # Переход в директорию проекта
 #            cd /root/str
 #
-#            # Проверка наличия docker-compose.yaml
 #            if [ ! -f docker-compose.yaml ]; then
 #              echo "docker-compose.yaml not found!"
 #              exit 1
 #            fi
 #            echo "docker-compose.yaml found."
 #
-#            # Создание файла .env с переменными окружения
+#            # Создание файла .env
 #            rm -f .env
 #            touch .env
 #            chmod 600 .env
@@ -317,9 +300,11 @@ jobs:
 #            cat .env
 #
 #            # Запуск docker compose
-#            docker compose pull || docker compose pull
-#            docker compose up -d --build || docker compose up -d --build
+#            docker compose pull
+#            docker compose up -d
 #
 #      - name: Notify success
 #        if: success()
 #        run: echo "Deployment was successful!"
+#
+#
